language: java
jdk:
- oraclejdk8

sudo: false
# as per http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/

# script for build and release via Travis to Bintray
script: gradle/buildViaTravis.sh

# cache between builds
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

env:
  global:
  - secure: 
  - secure: 
  - secure: 
  - secure: 
